version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5555:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
